//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVDxEvent
    {
        public int DVDxEventId { get; set; }
        public string DVDId { get; set; }
        public int EventTypeId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
    
        public virtual tDVD tDVD { get; set; }
        public virtual tEventType tEventType { get; set; }
        public virtual tUser tUser { get; set; }
    }
}
