//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVDxDisc
    {
        public int DVDxDiscId { get; set; }
        public string DVDId { get; set; }
        public string DescriptionSideA { get; set; }
        public string DescriptionSideB { get; set; }
        public string DiscIDSideA { get; set; }
        public string DiscIDSideB { get; set; }
        public string LabelSideA { get; set; }
        public string LabelSideB { get; set; }
        public bool DualLayeredSideA { get; set; }
        public bool DualLayeredSideB { get; set; }
        public bool DualSided { get; set; }
        public string Location { get; set; }
        public string Slot { get; set; }
    
        public virtual tDVD tDVD { get; set; }
    }
}
