//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDVDxAudio
    {
        public int DVDxAudioId { get; set; }
        public string DVDId { get; set; }
        public int AudioContentId { get; set; }
        public int AudioFormatId { get; set; }
        public int AudioChannelsId { get; set; }
    
        public virtual tAudioChannels tAudioChannels { get; set; }
        public virtual tAudioContent tAudioContent { get; set; }
        public virtual tAudioFormat tAudioFormat { get; set; }
        public virtual tDVD tDVD { get; set; }
    }
}
