//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEnhancedFeatures
    {
        public string DVDId { get; set; }
        public bool Feature1 { get; set; }
        public bool Feature2 { get; set; }
        public bool Feature3 { get; set; }
        public bool Feature4 { get; set; }
        public bool Feature5 { get; set; }
        public bool Feature6 { get; set; }
        public bool Feature7 { get; set; }
        public bool Feature8 { get; set; }
        public bool Feature9 { get; set; }
        public bool Feature10 { get; set; }
        public bool Feature11 { get; set; }
        public bool Feature12 { get; set; }
        public bool Feature13 { get; set; }
        public bool Feature14 { get; set; }
        public bool Feature15 { get; set; }
        public bool Feature16 { get; set; }
        public bool Feature17 { get; set; }
        public bool Feature18 { get; set; }
        public bool Feature19 { get; set; }
        public bool Feature20 { get; set; }
        public bool Feature21 { get; set; }
        public bool Feature22 { get; set; }
        public bool Feature23 { get; set; }
        public bool Feature24 { get; set; }
        public bool Feature25 { get; set; }
        public bool Feature26 { get; set; }
        public bool Feature27 { get; set; }
        public bool Feature28 { get; set; }
        public bool Feature29 { get; set; }
        public bool Feature30 { get; set; }
        public bool Feature31 { get; set; }
        public bool Feature32 { get; set; }
        public bool Feature33 { get; set; }
        public bool Feature34 { get; set; }
        public bool Feature35 { get; set; }
        public bool Feature36 { get; set; }
        public bool Feature37 { get; set; }
        public bool Feature38 { get; set; }
        public bool Feature39 { get; set; }
        public bool Feature40 { get; set; }
    
        public virtual tDVD tDVD { get; set; }
    }
}
