//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tExclusions
    {
        public int ExclusionId { get; set; }
        public string DVDId { get; set; }
        public Nullable<bool> MoviePick { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public Nullable<bool> IPhone { get; set; }
        public Nullable<bool> RemoteConnections { get; set; }
        public Nullable<bool> DPOPublic { get; set; }
        public Nullable<bool> DPOPrivate { get; set; }
    
        public virtual tDVD tDVD { get; set; }
    }
}
