//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLoanInfo
    {
        public int LoanInfoId { get; set; }
        public string DVDId { get; set; }
        public bool Loaned { get; set; }
        public Nullable<System.DateTime> Due { get; set; }
        public int UserId { get; set; }
    
        public virtual tDVD tDVD { get; set; }
        public virtual tUser tUser { get; set; }
    }
}
