//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLock
    {
        public int LockId { get; set; }
        public string DVDId { get; set; }
        public bool Entire { get; set; }
        public bool Covers { get; set; }
        public bool Title { get; set; }
        public bool MediaType { get; set; }
        public bool Overview { get; set; }
        public bool Regions { get; set; }
        public bool Genres { get; set; }
        public bool SRP { get; set; }
        public bool Studios { get; set; }
        public bool DiscInformation { get; set; }
        public bool Cast { get; set; }
        public bool Crew { get; set; }
        public bool Features { get; set; }
        public bool AudioTracks { get; set; }
        public bool Subtitles { get; set; }
        public bool EasterEggs { get; set; }
        public bool RunningTime { get; set; }
        public bool ReleaseDate { get; set; }
        public bool ProductionYear { get; set; }
        public bool CaseType { get; set; }
        public bool VideoFormats { get; set; }
        public bool Rating { get; set; }
    
        public virtual tDVD tDVD { get; set; }
    }
}
