//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tParentDVDxChildDVD
    {
        public int ParentDVDxChildDVDId { get; set; }
        public string ParentDVDId { get; set; }
        public string ChildDVDId { get; set; }
    
        public virtual tDVD tChildDVD { get; set; }
        public virtual tDVD tParentDVD { get; set; }
    }
}
