//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPurchase
    {
        public int PurchaseId { get; set; }
        public string DVDId { get; set; }
        public string PriceDenomination { get; set; }
        public Nullable<decimal> PriceValue { get; set; }
        public Nullable<int> PurchasePlaceId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool ReceivedAsGift { get; set; }
        public Nullable<int> GiftFromUserId { get; set; }
    
        public virtual tDVD tDVD { get; set; }
        public virtual tUser tUser { get; set; }
        public virtual tPurchasePlace tPurchasePlace { get; set; }
    }
}
