//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDVDxCast
    {
        public string DVDId { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string CollectionType { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public string Episode { get; set; }
        public string Group { get; set; }
        public string Role { get; set; }
        public string CreditedAs { get; set; }
        public bool Voice { get; set; }
        public bool Uncredited { get; set; }
        public bool Puppeteer { get; set; }
    }
}
