//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDVD
    {
        public string DVDId { get; set; }
        public string UPC { get; set; }
        public string Locality { get; set; }
        public string CollectionNumber { get; set; }
        public string CollectionType { get; set; }
        public bool IsPartOfOwnedCollection { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string OriginalTitle { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public Nullable<System.DateTime> Released { get; set; }
        public Nullable<int> RunningTime { get; set; }
        public string Rating { get; set; }
        public string CaseType { get; set; }
        public bool CaseSlipCover { get; set; }
        public string SRPDenomination { get; set; }
        public Nullable<decimal> SRPValue { get; set; }
        public string Overview { get; set; }
        public string EasterEggs { get; set; }
        public string SortTitle { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public int WishPriority { get; set; }
        public string Notes { get; set; }
    }
}
