//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEnhancedPurchaseInfo
    {
        public string DVDId { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string CollectionType { get; set; }
        public string Price1Denomination { get; set; }
        public Nullable<decimal> Price1Value { get; set; }
        public string Price2Denomination { get; set; }
        public Nullable<decimal> Price2Value { get; set; }
        public string Price3Denomination { get; set; }
        public Nullable<decimal> Price3Value { get; set; }
        public string Price4Denomination { get; set; }
        public Nullable<decimal> Price4Value { get; set; }
        public string Price5Denomination { get; set; }
        public Nullable<decimal> Price5Value { get; set; }
        public string Price6Denomination { get; set; }
        public Nullable<decimal> Price6Value { get; set; }
        public string CouponType { get; set; }
        public string CouponCode { get; set; }
        public string Price7Denomination { get; set; }
        public Nullable<decimal> Price7Value { get; set; }
        public string Price8Denomination { get; set; }
        public Nullable<decimal> Price8Value { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
    }
}
