//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFeatures
    {
        public string DVDId { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string CollectionType { get; set; }
        public bool SceneAccess { get; set; }
        public bool Commentary { get; set; }
        public bool Trailer { get; set; }
        public bool PhotoGallery { get; set; }
        public bool MakingOf { get; set; }
        public bool ProductionNotes { get; set; }
        public bool Game { get; set; }
        public bool DVDROMContent { get; set; }
        public bool MultiAngle { get; set; }
        public bool MusicVideos { get; set; }
        public bool Interviews { get; set; }
        public bool StoryboardComparisons { get; set; }
        public bool Outtakes { get; set; }
        public bool ClosedCaptioned { get; set; }
        public bool THXCertified { get; set; }
        public bool PictureInPicture { get; set; }
        public bool BDLive { get; set; }
        public bool BonusTrailers { get; set; }
        public bool DigitalCopy { get; set; }
        public bool DBOX { get; set; }
        public bool CineChat { get; set; }
        public bool PlayAll { get; set; }
        public bool MovieIQ { get; set; }
        public string OtherFeatures { get; set; }
    }
}
