//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFormat
    {
        public string DVDId { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string CollectionType { get; set; }
        public string AspectRatio { get; set; }
        public string VideoStandard { get; set; }
        public bool LetterBox { get; set; }
        public bool PanAndScan { get; set; }
        public bool C16X9 { get; set; }
        public bool DualSided { get; set; }
        public bool DualLayered { get; set; }
        public bool Color { get; set; }
        public bool BlackAndWhite { get; set; }
        public bool Colorized { get; set; }
        public bool Mixed { get; set; }
        public bool C2D { get; set; }
        public bool C3DAnaglyph { get; set; }
        public bool C3DBluRay { get; set; }
        public Nullable<bool> HDR10 { get; set; }
        public Nullable<bool> DolbyVision { get; set; }
    }
}
