//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vParentChildDVD
    {
        public string ParentDVDId { get; set; }
        public string ParentTitle { get; set; }
        public string ParentDistTrait { get; set; }
        public string ParentCollectionType { get; set; }
        public string ChildDVDId { get; set; }
        public string ChildTitle { get; set; }
        public string ChildDistTrait { get; set; }
        public string ChildCollectionType { get; set; }
    }
}
