//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.SQLDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPurchase
    {
        public string DVDId { get; set; }
        public string Title { get; set; }
        public string DistTrait { get; set; }
        public string CollectionType { get; set; }
        public string PriceDenomination { get; set; }
        public Nullable<decimal> PriceValue { get; set; }
        public string Place { get; set; }
        public string PlaceType { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool ReceivedAsGift { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
